In [5]:
import re
import os
import pandas as pd

In [2]:
!pip install pandas

Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting pandas
  Downloading https://mirrors.aliyun.com/pypi/packages/4c/33/87b15a5baeeb71bd677da3579f907e97476c5247c0e56a37079843af5424/pandas-1.2.2-cp37-cp37m-manylinux1_x86_64.whl (9.9 MB)
     |████████████████████████████████| 9.9 MB 567 kB/s eta 0:00:01     |██████████████████▌             | 5.7 MB 795 kB/s eta 0:00:06     |██████████████████████████████▏ | 9.3 MB 1.2 MB/s eta 0:00:01
Requirement already satisfied: python-dateutil>=2.7.3 in /miniconda/lib/python3.7/site-packages (from pandas) (2.8.1)
Collecting pytz>=2017.3
  Downloading https://mirrors.aliyun.com/pypi/packages/70/94/784178ca5dd892a98f113cdd923372024dc04b8d40abe77ca76b5fb90ca6/pytz-2021.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 3.1 MB/s eta 0:00:01
Requirement already satisfied: numpy>=1.16.5 in /miniconda/lib/python3.7/site-packages (from pandas) (1.18.1)
Requirement already satisfied: six>=1.5 in /miniconda/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas) (1.14.0)
Installing collected packages: pytz, pandas
Successfully installed pandas-1.2.2 pytz-2021.1

In [3]:
datafile = []
for dirname, _, filenames in os.walk('/bagging/data'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
        if 'json' in os.path.join(dirname, filename):
            datafile.append(os.path.join(dirname, filename))

/bagging/data/.DS_Store
/bagging/data/output.xls
/bagging/data/sim.txt
/bagging/data/test.xls
/bagging/data/test0301.xls
/bagging/data/train.zip
/bagging/data/三井住友.xls
/bagging/data/三井住友.xlsx
/bagging/data/主营产品梳理.xlsx
/bagging/data/解放贷款车.xls
/bagging/data/AMAT-INTEL-AIR/.DS_Store
/bagging/data/AMAT-INTEL-AIR/AMAT-INTEL-AIR.json
/bagging/data/ANA - BAE Systems - IN/ANA - BAE Systems - IN.json
/bagging/data/AUX-SEMB CORP-运单/AUX-SEMB CORP-运单.json
/bagging/data/AUX-WCS - Catalent - IN/AUX-WCS - Catalent - IN.json
/bagging/data/GIST钢瓶-INTEL-海运进境/GIST钢瓶-INTEL-海运进境.json
/bagging/data/SIN_OUT-CAM PLAS/SIN_OUT-CAM PLAS.json
/bagging/data/SIN_OUT-South East Asia Moulding/SIN_OUT-South East Asia Moulding.json
/bagging/data/awb1/awb1.json
/bagging/data/cdn1/cdn1.json
/bagging/data/layoutlm/config.json
/bagging/data/layoutlm/pytorch_model.bin
/bagging/data/layoutlm/special_tokens_map.json
/bagging/data/layoutlm/tokenizer_config.json
/bagging/data/layoutlm/training_args.bin
/bagging/data/layoutlm/vocab.txt
/bagging/data/swb1/swb1.json
/bagging/data/swb10/swb10.json
/bagging/data/swb11/swb11.json
/bagging/data/swb2/swb2.json
/bagging/data/swb3/swb3.json
/bagging/data/swb4/swb4.json
/bagging/data/swb5/swb5.json
/bagging/data/swb6/swb6.json
/bagging/data/swb7/swb7.json
/bagging/data/swb8/swb8.json
/bagging/data/swb9/swb9.json
/bagging/data/万历-LV-Honour Century/万历-LV-Honour Century.json
/bagging/data/万历-LV-Infinity Global Europe, BV/万历-LV-Infinity Global Europe, BV.json

In [7]:
# df = pd.read_excel('/bagging/data/test0301.xls', header=[1], skiprows=[2], )
df = pd.read_excel('/bagging/data/test0301.xls', header=[0])
# 抽取 [首付款|GPS费|保险费(交强险)|保险费(商业险)|杂费|落户保证金|还款保证金|落户费|附加税|服务费|主车|挂车|有定金|实付]
df[['付款事由']]
# df

                                                 付款事由
0   付 王玉莲 车款：370000元（主车370000元，挂车0元）,有定金：10000元）,有...
1   付 张树春 车款：312000元（主车312000元，挂车0元）,有定金：10000元）,有...
2   付 韩云成 车款：370000元（主车370000元，挂车0元）,有定金：10000元）,有...
3   付 韩龙军 车款：370000元（主车370000元，挂车0元）,有定金：10000元）,有...
4   付 陈立凤 车款：390000元（主车325000元，挂车65000元）,有定金：5000元...
..                                                ...
77  付 乔丽平 车款：430000元（主车430000元，挂车0元）,有定金：10000元）,有...
78  付 于忠秋 车款：360000元（主车360000元，挂车0元）,有定金：20000元）,有...
79  付 胡士良 车款：340000元（主车340000元，挂车0元）,有定金：10000元）,有...
80  付 黄艳艳 车款：390000元（主车325000元，挂车65000元）,有定金：20000...
81  付 付晓冬 车款：390000元（主车325000元，挂车65000元）,有定金：20000...

[82 rows x 1 columns]

In [8]:
df.columns

Index(['业务日期', '合同编号', '客户名称', '主车档案号', '车架号', '挂车档案号', '放贷银行', '贷款金额',
       '实收首付金额', '申请付款金额', '付款类型', '付款事由', '审批付款金额', '首付款', 'GPS费', '保险费(交强险)',
       '保险费(商业险)', '杂费', '落户保证金', '还款保证金', '落户费', '附加税', '服务费', '主车', '挂车',
       '有定金', '实付', '费用小计', 'Unnamed: 28', 'Unnamed: 29', 'GPS费.1',
       '保险费(交强险).1', '保险费(商业险).1', '落户费.1', '附加税.1', '费用小计.1', 'Unnamed: 36',
       '落户保证金.1', '还款保证金.1', '押金小计', 'Unnamed: 40', 'GPS费.2', '保险费(交强险).2',
       '保险费(商业险).2', '杂费.1', '落户费.2', '附加税.2', '服务费.1', '利润小计', 'Unnamed: 49',
       '利润', 'Unnamed: 51', '放款情况'],
      dtype='object')

In [11]:
for idx, row in df.iterrows():
    dict_res = all_search(row['付款事由'])
    for k, v in dict_res.items():
        if v != '':
#             print('k: {}, v:{}'.format(k, v))
            df[k][idx] = v
df

/miniconda/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,业务日期,合同编号,客户名称,主车档案号,车架号,挂车档案号,放贷银行,贷款金额,实收首付金额,申请付款金额,...,保险费(商业险).2,杂费.1,落户费.2,附加税.2,服务费.1,利润小计,Unnamed: 49,利润,Unnamed: 51,放款情况
0,2021-2-27,YWHT2021022700004,王玉莲,NaN,LFWSRXSJ7M1F02931,NaN,鸡西祥月支行,370000,41900,360000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-2-27,YWHT2021022700003,张树春,NaN,LFWSRXSJ6M1F10406,NaN,平安银行哈尔滨分行营业部,312000,32480,302000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-2-27,YWHT2021022700002,韩云成,NaN,LFWSRXSJ2M1F02934,NaN,平安银行哈尔滨分行营业部,370000,41900,360000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-2-27,YWHT2021022700001,韩龙军,NaN,LFWSRXSJ5M1F02930,NaN,平安银行哈尔滨分行营业部,370000,41900,360000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-2-25,YWHT2021022500006,陈立凤,NaN,LA99L40Z6M0JTM014/LFWSRXSJ8L1E78296,NaN,鸡西祥月支行,400000,58800,385000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,2021-1-29,YWHT2021012900002,乔丽平,HGCX2010177801,LFWSRXSJ1L1F53257,NaN,鸡西祥月支行,300000,157000,420000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,2021-1-25,YWHT2021012100008,于忠秋,HGCX2004175057,LFNKRXRP2L1F08858,NaN,鸡西祥月支行,250000,150000,340000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,2021-1-14,YWHT2021011400007,胡士良,NaN,LFWSRXSJ1M1F06146,NaN,平安银行哈尔滨分行营业部,340000,40380,330000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,2021-1-9,YWHT2021010900010,黄艳艳,NaN,LA99FRZ31M0ZYC065/LFWSRXSJ3L1E68999,NaN,平安银行哈尔滨分行营业部,400000,45800,370000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,2021-1-9,YWHT2021010900007,付晓冬,NaN,LA99FRZ38M0ZYC063/LFWSRXSJ7L1F62562,NaN,平安银行哈尔滨分行营业部,400000,45800,370000.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.to_excel('/bagging/data/output0301.xls', index=None)

/miniconda/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: As the xlwt package is no longer maintained, the xlwt engine will be removed in a future version of pandas. This is the only engine in pandas that supports writing in the xls format. Install openpyxl and write to an xlsx file instead. You can set the option io.excel.xls.writer to 'xlwt' to silence this warning. While this option is deprecated and will also raise a warning, it can be globally set and the warning suppressed.
  """Entry point for launching an IPython kernel.

In [65]:
!pip install xlwt

Looking in indexes: https://mirrors.aliyun.com/pypi/simple
Collecting xlwt
  Downloading https://mirrors.aliyun.com/pypi/packages/44/48/def306413b25c3d01753603b1a222a011b8621aed27cd7f89cbc27e6b0f4/xlwt-1.3.0-py2.py3-none-any.whl (99 kB)
     |████████████████████████████████| 99 kB 2.4 MB/s eta 0:00:011
Installing collected packages: xlwt
Successfully installed xlwt-1.3.0

In [36]:
t = '付 刘永义 车款：385000元（主车385000元，挂车0元）,有定金：10000元）,有代收款：0元，实付：375000元,费用明细：(首付款0元,GPS费:1000元,保险费(交强险):5000元,保险费(商业险):15000元,服务费:18100元,杂费:2000元,落户保证金:2000元,还款保证金:5000元 合计48100元).'
t

'付 刘永义 车款：385000元（主车385000元，挂车0元）,有定金：10000元）,有代收款：0元，实付：375000元,费用明细：(首付款0元,GPS费:1000元,保险费(交强险):5000元,保险费(商业险):15000元,服务费:18100元,杂费:2000元,落户保证金:2000元,还款保证金:5000元 合计48100元).'

In [10]:

# 抽取 [首付款|GPS费|保险费(交强险)|保险费(商业险)|杂费|落户保证金|还款保证金|落户费|附加税|服务费|主车|挂车|有定金|实付]
def _search(t):
    res = {
        '首付款': '',
        'GPS费': '',
        '保险费(交强险)': '',
        '保险费(商业险)': '',
        '杂费': '',
        '落户保证金': '',
        '还款保证金': '',
        '落户费': '',
        '附加税': '',
        '服务费': '',
        '主车': '',
        '挂车': '',
        '有定金': '',
        '实付': ''
    }
    # 首付款
    sfk = re.compile('首付款.{0,3}?([0-9]+)')
    r_sfk = re.search(sfk, t)
    if r_sfk:
        res['首付款'] = r_sfk.groups()[-1]
    # GPS费
    gps = re.compile('GPS费.{0,3}?([0-9]+)')
    r_gps = re.search(gps, t)
    if r_gps:
        res['GPS费'] = r_gps.groups()[-1]
    # 保险费(交强险)
    bxf = re.compile('保险费.{0,1}交强险.{0,3}?([0-9]+)')
    r_bxf = re.search(bxf, t)
    if r_bxf:
        res['保险费(交强险)'] = r_bxf.groups()[-1]
    # 保险费(商业险)
    bxf_sy = re.compile('保险费.{0,1}商业险.{0,3}([0-9]+)')
    r_bxf_sy = re.search(bxf_sy, t)
    if r_bxf_sy:
        res['保险费(商业险)'] = r_bxf_sy.groups()[-1]
    # 杂费
    zf = re.compile('杂费.{0,3}?([0-9]+)')
    r_zf = re.search(zf, t)
    if r_zf:
        res['杂费'] = r_zf.groups()[-1]
    # 落户保证金
    
    print(res)

def sub_search(p, t):
    pattern = re.compile(p+'.{0,3}?([0-9]+)')
    res = re.search(pattern, t)
    if res:
        return res.groups()[-1]
    return ''

def all_search(t):
    res = {
        '首付款': '',
        'GPS费': '',
        '保险费(交强险)': '',
        '保险费(商业险)': '',
        '杂费': '',
        '落户保证金': '',
        '还款保证金': '',
        '落户费': '',
        '附加税': '',
        '服务费': '',
        '主车': '',
        '挂车': '',
        '有定金': '',
        '实付': ''
    }
    for k, v in res.items():
        if '(' in k:
            p = k.replace('(', '.{0,1}')
            p = p.replace(')', '')
#             print(p)
        else:
            p = k
        res[k] = sub_search(p, t)
    return res

print(all_search(t))

NameError: name 't' is not defined

In [152]:
df_rm = pd.read_excel('/bagging/data/rm.xls', dtype='str')
df_rm

,销货单位,购货单位,采购日期,数量,公告车型,采购金额,发动机号码,车架号码,购货单位.1,销售金额,销售日期
0,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2017-01-01 00:00:00,1,CA4250P66K25T1A1E5,258215.14,52862038,LFNFVXRX4H1F28507,孙力成,250000,2017-01-11 00:00:00
1,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2017-04-01 00:00:00,1,CA4250P66K24T1A1E5,350603.63,52828818,LFWSRXSJ5H1E22467,范洪洋,344000,2017-04-01 00:00:00
2,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2017-04-01 00:00:00,1,CA4250P66K25T1A1E5,375876.59,52833885,LFWSRXSJ1H1E21929,哈尔滨柏威大件运输有限责任公司,374000,2017-04-01 00:00:00
3,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2017-04-01 00:00:00,1,CA4250P66K24T1A1E5,360603.63,52836348,LFWSRXSJ6H1F21699,哈尔滨杰邦博瑞运输有限公司,354000,2017-04-01 00:00:00
4,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2017-04-01 00:00:00,1,CA4250P66K24T1A1E5,355510.01,52823942,LFWSRXSJ8H1F17007,哈尔滨市佰亿货物运输有限责任公司,355000,2017-04-01 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...
1095,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2018-12-17 00:00:00,1,CA4250P66K24T1A1E5,352475.247524752,53097630,LFWSRXSJ6J1F50299,臧红雨,356000,2018-12-17 00:00:00
1096,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2018-12-24 00:00:00,1,CA3310P66K24L6T4AE5,405940.594059406,53117102,LFNMVXSX2J1F57117,哈尔滨市佰亿货物运输有限责任公司,410000,2018-12-24 00:00:00
1097,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2018-12-24 00:00:00,1,CA3310P66K24L6T4AE5,237623.762376238,53117145,LFNMVXSX2J1F57118,哈尔滨市佰亿货物运输有限责任公司,240000,2018-12-24 00:00:00
1098,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2018-12-24 00:00:00,1,CA3310P66K24L6T4AE5,237623.762376238,53116271,LFNMVXSX0J1F57115,哈尔滨市佰亿货物运输有限责任公司,240000,2018-12-24 00:00:00
1099,一汽解放汽车销售有限公司,哈尔滨路遥汽车销售有限公司,2018-12-24 00:00:00,1,CA3310P66K24L6T4AE5,405940.594059406,53116277,LFNMVXSX0J1F57116,哈尔滨市佰亿货物运输有限责任公司,410000,2018-12-24 00:00:00

In [ ]:
# 发动机号码    车架号码

In [153]:
df_rm['新发动机号码'] = df_rm['发动机号码']
df_rm['新发动机号码']

0       52862038
1       52828818
2       52833885
3       52836348
4       52823942
          ...
1095    53097630
1096    53117102
1097    53117145
1098    53116271
1099    53116277
Name: 新发动机号码, Length: 1100, dtype: object

In [158]:
df_rm['新车架号码'] = df_rm['车架号码']
df_rm['新车架号码']

0       LFNFVXRX4H1F28507
1       LFWSRXSJ5H1E22467
2       LFWSRXSJ1H1E21929
3       LFWSRXSJ6H1F21699
4       LFWSRXSJ8H1F17007
              ...
1095    LFWSRXSJ6J1F50299
1096    LFNMVXSX2J1F57117
1097    LFNMVXSX2J1F57118
1098    LFNMVXSX0J1F57115
1099    LFNMVXSX0J1F57116
Name: 新车架号码, Length: 1100, dtype: object

In [159]:
for idx, row in df_rm[df_rm.duplicated('车架号码')].iterrows():
    if pd.isnull(row['车架号码']):
#         print(idx)
        continue
    df_rm['新车架号码'][idx] = _new(row['车架号码'], df_rm, '新车架号码', 3)

In [161]:
df_rm.to_excel('/bagging/data/res_rm.xls', index=None)

In [154]:
'52862038' in df_rm['新发动机号码'].values

True

In [155]:
df_rm[['发动机号码']][df_rm.duplicated('发动机号码')]

         发动机号码
443   52949087
470   52944996
478   52950799
479   52963090
480   52958941
...        ...
1082  53029536
1084  53109890
1085  53098476
1086  53089559
1094       NaN

[155 rows x 1 columns]

In [157]:
for idx, row in df_rm[df_rm.duplicated('发动机号码')].iterrows():
    if pd.isnull(row['发动机号码']):
#         print(idx)
        continue
    df_rm['新发动机号码'][idx] = _new(row['发动机号码'], df_rm, '新发动机号码', 3)

In [156]:
def _new(x, df, col_name, last=2):
    int_last = int(x[-last:])
    for i in range(int_last, 10**last):
        if x[:-last]+str(i) not in df[col_name].values:
#             print(x[:-last]+str(i))
            return x[:-last]+str(i)
    print('-----')

In [144]:
o = _new(df_rm['发动机号码'][470], df_rm, '新发动机号码')

52944997